version: '3.2'
services:
    nginx:
        container_name: nginx
        image: nginx:v1
        volumes:
            - ./:/var/www
        environment:
            - "DB_CONNECTION=pgsql"
            - "DB_HOST=db"
            - "DB_PORT=5432"
            - "DB_DATABASE=MethodSovet"
            - "DB_USERNAME=postgres"
            - "DB_PASSWORD=root"
            - "XDG_CONFIG_HOME=/app"
        ports:
            - "8080:80"
        links:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        container_name: app
        image: php-fpm:v1
        volumes:
            - ./:/var/www
        environment:
            - "DB_CONNECTION=pgsql"
            - "DB_HOST=db"
            - "DB_PORT=5432"
            - "DB_DATABASE=MethodSovet"
            - "DB_USERNAME=postgres"
            - "DB_PASSWORD=root"
        links:
            - db
        networks:
            - app-network

    db:
        image: postgres:14.10
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_DB: MethodSovet
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        volumes:
            - ./MethodSovet.sql:/docker-entrypoint-initdb.d/MethodSovet.sql
        ports:
            - "5452:5432"
        networks:
            - app-network

networks:
    app-network:
